on: [pull_request]

jobs:
  github-action-show-version:
    runs-on: ubuntu-latest
    name: Next version is
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Analyze commits
        uses: ./ # Uses an action in the root directory
        id: hello
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}